---
# Configuration inspir√©e de https://gethomepage.dev/configs/services/#docker
- Docker:
    - Conteneurs:
        type: docker
        server: homepage-docker
        showStats: true
        showList: true
